<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * The report model is used to interact with reports about the 
 * study habits of students.
 * Reports are generated by students when they request for them
 * and they are stored if they want to do so.
 */
class Report extends Model
{
    /**
     * Mass Assignable Variables
     *
     * @var array
     */
    protected $fillable = [
        'no_modules', 'sessions_completed', 'sessions_missed', 
        'sessions_incomplete', 'progress', 'sessions', 
        'time_spent', 'study_times', 'module_ratings', 'predictions',
        'sessiondetails'
    ];

    /**
     * Schedule Relationship
     *
     * @return Relationship
     */
    public function schedule()
    {
        return $this->belongsTo('App\Schedule');
    }
}
