<option value="Arts">Arts</option>
<option value="History">History</option>
<option value="Languages and literature">Languages and literature</option>
<option value="Philosophy">Philosophy</option>
<option value="Theology">Theology</option>
<option value="Anthropology">Anthropology</option>
<option value="Archaeology">Archaeology</option>
<option value="Economics">Economics</option>
<option value="Human geography">Human geography</option>
<option value="Law">Law</option>
<option value="Political science">Political science</option>
<option value="Psychology">Psychology</option>
<option value="Sociology">Sociology</option>
<option value="Biology">Biology</option>
<option value="Chemistry">Chemistry</option>
<option value="Earth sciences">Earth sciences</option>
<option value="Space sciences">Space sciences</option>
<option value="Physics">Physics</option>
<option value="Computer Science">Computer Science</option>
<option value="Mathematics">Mathematics</option>
<option value="Statistics">Statistics</option>
<option value="Engineering and technology">Engineering and technology</option>
<option value="Medicine and health">Medicine and health</option>
<option value="Other">Other</option>